### ISSUE TITLE
rfrugalsim gives error when the pre-existing dataset only has one column

### ISSUE THREAD

**Issue by XiLinStats** [rje42/causl#12]
Example:

forms <- list(list(),
              list(A ~ U),
              list(Y ~ A),
              list(~ 1))
fams <- list(integer(0), 5, 1, 1)
pars <- list(A = list(beta=c(0,1)),
             Y = list(beta=c(1, 1), phi=1),
             cop = list(beta=-1))

dat <- data.frame(U = rep(1,100))
dat <- rfrugalParam(formulas=forms, family=fams, pars=pars, dat=dat)
Error in eval(predvars, data, env) : object 'U' not found

This is due to the function causl:::gen_dummy_dat(). **dat[1,]** does not give the column name when dat only has one column. 

![image](https://github.com/rje42/causl/assets/93380443/1989127a-d809-435d-94d0-53222c56d56b)

Thinking about what the best way to fix this is...

**Comment by rje42** [comment]
Sorted - just needed a `drop=FALSE` argument!
