### ISSUE TITLE
fitCausal does not give the right copula estimates with binary covariates

### ISSUE THREAD

**Issue by XiLinStats** [rje42/causl#13]
I remember that we have fixed this before. A version control issue?

library(causl)
library(data.table)
n <- 2000

family  <- list(c(1,5), c(5),1,1)
forms <- list(c(X1 ~ 1,X2 ~ 1),
              list(A ~ X1 + X2),
              Y ~ A ,
              ~ 1)

pars <- list(X1 = list(beta = 0,phi = 1),
             X2 = list(beta = 0),
             A = list(beta = c(1,1,1)),
             Y = list(beta = c(1,1),phi = 1),
             cop = list(beta = matrix(c(0.1,0.5,0.5),nrow = 1)))

dat <- as.data.table(causl:::rfrugalParam(n = n, formulas = forms, family = family, pars = pars))

modY <- fitCausal(dat, formulas = unlist(forms[-2]),
                  family = unlist(family[-2]), control=list(maxit=2e3, newton=TRUE),
                  sandwich = F)

modY

modY
log-likelihood:  -6919.401 
X1 ~ 1
                est.   s.e.
(intercept) -0.00526 0.0219
  residual s.e.:  0.962 0.0304 

Y ~ A
             est.   s.e.
(intercept) 0.996 0.0483
A           0.983 0.0553
  residual s.e.:  0.953 0.0303 

X2 ~ 1
            est.   s.e.
(intercept) 0.02 0.0447
copula parameters:
cop ~ 1
             est.   s.e.
cop_X1_Y   0.4633 0.0476
cop_X1_X2 -0.0979 0.0561
cop_Y_X2   0.0223 0.0565

**Comment by XiLinStats** [comment]
It seems like a version control issue. An early branch https://github.com/XiLinStats/causl/tree/DGcop_fix_new worked fine. I am going to investigate the difference.
modY
log-likelihood:  -6974.867 
X1 ~ 1
               est.   s.e.
(intercept) -0.0223 0.0224
  residual s.e.:  1 0.0317 

X2 ~ 1
               est.   s.e.
(intercept) 0.00854 0.0447
Y ~ A
             est.   s.e.
(intercept) 0.994 0.0473
A           1.006 0.0548
  residual s.e.:  NA NA 

copula parameters:
cop ~ 1
           est.   s.e.
cop_X1_X2 0.151 0.0562
cop_X1_Y  0.518 0.0473
cop_X2_Y  0.448 0.0578

**Comment by rje42** [comment]
I think the resolution to this is to allow `fitCausal` to fit the pair-copula parameters. We can also implement the inversion method for the multivariate copula
