### ISSUE TITLE
New fitCausal produces error

### ISSUE THREAD

**Issue by chasehmathis** [rje42/causl#17]
# error in fitting
remotes::install_github("https://github.com/rje42/causl")
library(causl)
set.seed(1129)
# formulae corresponding to covariates, treatments, outcomes and the dependence
forms <- list(list(Z1 ~ 1, Z2 ~ 1), list(X1 ~ Z1 + Z2),
              list(Y1 ~ X1 ), ~ 1)

fam <- list(c(3,1), 1, 1, 1)
# list of parameters, including 'beta' (regression params) and 'phi' dispersion
pars <- list(Z1 = list(beta=c(log(1)), phi=1),
             Z2 = list(beta = log(1), phi = 1),
             X1 = list(beta=c(-0.2, 0.5, 0.2), phi = 1),
             Y1 = list(beta=c(-0.4,0.3), phi=1),
             cop =list(beta = matrix(c(0.5, 0.25, 0.5), byrow = TRUE, nrow = 1)))

n <- 200

dat <- rfrugalParam(n, forms, fam, pars)

> out <- fit_causl(dat, formulas = list(Y1~ X1, Z1~1, Z2~1, ~1), family = c(1,3,3,1))

Error in (function (par, fn, gr = NULL, ..., method = c("Nelder-Mead",  : 
  function cannot be evaluated at initial parameters
  
 This error was produced on a virtual machine set up from scratch.

**Comment by rje42** [comment]
There is a mismatch in your family variables.  `Z2` is simulated as a normal, but then fitted as an exponential.  If you change this either way to make them consistent, the error disappears
